[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "organization_id-custom_component_id"
description = 'Custom Haystack component to be used with deepset Cloud'
readme = "README.md"
requires-python = ">=3.10,<3.13" # deepset cloud at the moment uses 3.10
license = "MIT"
keywords = []
authors = [{ name = "deepset", email = "platform-engineering-exploration@deepset.de" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "haystack-ai>=2.0.0",
  "amazon-bedrock-haystack>=0.9.0",
  "opensearch-haystack>=0.3.0",
  "huggingface_hub==0.23.2", # Temporary pin + explicit mention till fix from https://github.com/huggingface/setfit/pull/527 is available
  "sentence-transformers>=2.2.0",
  "setfit==1.0.3",
  "nltk==3.8.1",
  "mmh3==4.1.0",
  "pdf2image>=1.16.3",
  "deepl>=1.18.0",
  "huggingface-hub<0.25.0"
]
dynamic = ["version"]

[tool.hatch.version]
path = "src/__about__.py"

[[tool.hatch.envs.all.matrix]]
python = ["3.10", "3.11"]


[tool.hatch.build.targets.wheel]
packages = ["src/organization_id-custom_component_id"]